# ESTO ES UN COMENTARIO
# Todo lo que está a la derecha de # es solo para nosotros

version: 0.3.5 # NO TOCAR

# HODL username
# username: "Vanetizen22" # < TU_USUARIO@hodl.ar

# NOSTR Settings
# nostr: # Sin el # adelante
#   npub: "npub14d3nspk90v440q9h70g39h4w4nacy4wgnfhezve3qhdtngxp2smspn85ua" # Entre comillas dobles

# Configuración Global
html:
# title: Este valor no funciona porque esta comentado
  title: Links | Vanessa # Este es el Título que aparece en la pestaña de navegador

# Colores de plantilla
theme:
  background_color: "#f9fafb"
  # cover_color: "#ff7070"

# Configuración Central
main:
  title: Vanessa22 # Aca podes poner tu nombre o el de tu producto

# Lista de bloques
blocks:
  # Estos bloques los podes editar cambiando SOLO el texto que está en blanco
  # Sacale 

  - title: Instagram
    icon: instagram
    url: https://www.instagram.com/moon1vane?igsh=b2drYWdtc3oxMjk0

# - title: Twitter
#   icon: twitter
#   url: https://twitter.com/eugeOv19
    
# - title: LinkedIn # Este es el nombre del botón
#   icon: linkedin # Este es el nombre del icono (si queres añadir una red social nueva, prestá atencion que es todo con minúscula)
#   url: https://linkedin.com/in/TU-USUARIO # Link a donde redireccionará al hacer click

# - title: Github
#   icon: github
#   url: https://github.com/Vanetizen22

# - title: Sitio Web
#   icon: url
#   url: https://www.TU-WEB.com

# - title: Telegram
#   icon: telegram
#   url: https://t.me/Vaneb21
    
# Guardá el archivo haciendo click en Commit Changes, abajo
# Volvé a las instrucciones
